osx_image: xcode11.3
laguage: objective-c
branches:
  only:
    - develop
    - master
notification:
  email: false
install:
  - gem install bundler
  - bundle install
script: bundle exec fastlane ios bonjour